// Real parts from Mikes Montes and other G-Body vendors
const MIKES_MONTES_PARTS = [
  {
    id: 'mm-1',
    name: 'Monte Carlo SS 9pc Door and Trunk Weatherstrip Seal Kit',
    price: 199.99,
    category: 'Seals & Weatherstripping',
    image: '/images/cars/placeholder.jpg',
    url: 'https://www.mikesmontes.com/Monte-Carlo-SS-9-pc-Door-and-Trunk-Weatherstrip-Seal-Kit_p_1960.html',
    source: 'Mikes Montes',
    fits: ['Monte Carlo SS 1983-1988'],
  },
  {
    id: 'mm-2',
    name: 'Power Window and Lock Switches',
    price: 49.99,
    category: 'Interior',
    image: '/images/cars/placeholder.jpg',
    url: 'https://www.mikesmontes.com/Power-Window-and-Lock-Switches_p_2560.html',
    source: 'Mikes Montes',
    fits: ['Monte Carlo', 'Grand National', 'Cutlass', 'Regal', 'El Camino'],
  },
  {
    id: 'mm-3',
    name: 'Carpeted Floor Mats - Large Gray Monte Carlo SS Logo',
    price: 112.99,
    category: 'Interior',
    image: '/images/cars/placeholder.jpg',
    url: 'https://www.mikesmontes.com/',
    source: 'Mikes Montes',
    fits: ['Monte Carlo SS'],
  },
  {
    id: 'mm-4',
    name: '8pc Stainless Steel and 6 pc Seal T-Top Kit',
    price: 529.00,
    category: 'Exterior',
    image: '/images/cars/placeholder.jpg',
    url: 'https://www.mikesmontes.com/',
    source: 'Mikes Montes',
    fits: ['Monte Carlo SS Aerocoupe'],
  },
  {
    id: 'mm-5',
    name: 'Windshield Washer Bottle and Coolant Overflow Bottle Set',
    price: 64.95,
    category: 'Engine',
    image: '/images/cars/placeholder.jpg',
    url: 'https://www.mikesmontes.com/',
    source: 'Mikes Montes',
    fits: ['All G-Body'],
  },
  {
    id: 'mm-6',
    name: 'Door Seals Weatherstrip Kit',
    price: 54.99,
    category: 'Seals & Weatherstripping',
    image: '/images/cars/placeholder.jpg',
    url: 'https://www.mikesmontes.com/',
    source: 'Mikes Montes',
    fits: ['Monte Carlo', 'Grand National', 'Regal'],
  },
  {
    id: 'mm-7',
    name: 'New Maroon Console Door Lid with Hinge',
    price: 89.95,
    category: 'Interior',
    image: '/images/cars/placeholder.jpg',
    url: 'https://www.mikesmontes.com/',
    source: 'Mikes Montes',
    fits: ['Monte Carlo SS'],
  },
  {
    id: 'mm-8',
    name: '4 Door Strap Ends and Covers',
    price: 29.99,
    category: 'Interior',
    image: '/images/cars/placeholder.jpg',
    url: 'https://www.mikesmontes.com/',
    source: 'Mikes Montes',
    fits: ['Monte Carlo 1978-1985', 'Malibu 1978-1987', 'El Camino'],
  },
];

const PART_CATEGORIES = [
  'All Parts',
  'Engine',
  'Transmission',
  'Suspension',
  'Brakes',
  'Exhaust',
  'Interior',
  'Exterior',
  'Seals & Weatherstripping',
  'Electrical',
  'Body Panels',
];

export { MIKES_MONTES_PARTS, PART_CATEGORIES };